name: Backend workflow


on: [ push, pull_request ]


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installing dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install pipenv pytest
          pipenv install . --system --deploy --ignore-pipfile

      - name: Running tests
        working-directory: ./backend
        run: pytest
